[build]
  publish = "build"
  command = "node scripts/createEnv.js && NODE_ENV=production yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "https://www.hoyohub.com/*"
  to = "https://hoyohub.com/:splat"
  status = 301
  force = true
